### ISSUE TITLE
Bug in router

### ISSUE THREAD

**Issue by ovekyc** [sv-bootcamp/goober#127]
There is still bug in #126 .
After finish function '/savedpost' or '/createdpost'. Express call '/:id' function.
It was solved as hacky way now so we need to find more better solution.

**Comment by festinalente91** [comment]
I think api/user/:userId/savedpost is much proper to represent some specific users's savuedpost as url in our REST API.

**Comment by ochanje210** [comment]
please resolve this issue ASAP. this is totally a blocker for our release date now

**Comment by ovekyc** [comment]
It seems like there is no clear way to resolve.
For the best, I think we need to check req.params and handle it manually.
Refer link below
http://expressjs.com/en/4x/api.html#router
http://stackoverflow.com/questions/31493190/express-parameterized-route-conflict
http://stackoverflow.com/questions/31899854/express-routes-are-conflicting

**Comment by ovekyc** [comment]
#130

**Comment by ovekyc** [comment]
#133
