### ISSUE TITLE
Reponse Status code when dont have permission

### ISSUE THREAD

**Issue by ovekyc** [sv-bootcamp/goober#135]
Currently, when i send request with no permission (invalid token or something) It response with status code 500.
It is not a RESTful-tic. we should change it
https://en.wikipedia.org/wiki/HTTP_403

**Comment by ochanje210** [comment]
so it should be 403?

**Comment by ovekyc** [comment]
Without permission? Yes

**Comment by ochanje210** [comment]
why getting 500 is not a RESTful?

**Comment by ovekyc** [comment]
500 means internal server error generally which does not match with no-permission

**Comment by ochanje210** [comment]
understood.

**Comment by festinalente91** [comment]
lgtm

**Comment by ovekyc** [comment]
#144
