### ISSUE TITLE
Database autoincrement

### ISSUE THREAD

**Issue by ovekyc** [sv-bootcamp/goober#27]
We need some clear and cool way to deal a increment in database

**Comment by fguy** [comment]
Why?

**Comment by fguy** [comment]
https://www.quora.com/How-do-you-generate-monotonically-increasing-sequence-numbers-seqnums-in-a-large-distributed-system

**Comment by festinalente91** [comment]
we are going to make unique key 
https://github.com/broofa/node-uuid

**Comment by fguy** [comment]
This seems more popular: https://www.npmjs.com/package/uuid4

**Comment by ovekyc** [comment]
But node-uuid has more stars on repo!

**Comment by ovekyc** [comment]
We gonna use **uuid4**. Not node-uuid
