### ISSUE TITLE
Travis Heroku Continuous Deployment

### ISSUE THREAD

**Issue by festinalente91** [sv-bootcamp/goober#28]
To auto deployment using travis, I need to put api key info in travis.yml file. 
However uploading api key ( even though it's encrypted ) is not a good idea.
I need to connect git repository with out upload heroku api

**Comment by fguy** [comment]
Use env var.

**Comment by festinalente91** [comment]
I found out that I can just connect github repo to heroku, if I have admin access :)
thank you @fguy
